In [33]:
import numpy as np
import pandas as pd

In [34]:
# Home directory
basedir = "C:/Users/isaac/Box/CellBio-MajorLab/Users/Isaac/Experiments/035_SSandGSK3B_kingfisher_phospho/DIANN_output"

In [35]:
# Load the peptides matrix
pr_matrix = pd.read_csv(f"{basedir}/report.pr_matrix.tsv", sep="\t", index_col=0)
pg_matrix = pd.read_csv(f"{basedir}/report.pg_matrix.tsv", sep="\t", index_col=0)

# Samples info
conditions = pd.read_csv(f"{basedir}/Conditions.csv")
comparisons = pd.read_csv(f"{basedir}/Comparisons.csv")

In [36]:
pr_matrix

,Protein.Ids,Protein.Names,Genes,First.Protein.Description,Proteotypic,Stripped.Sequence,Modified.Sequence,Precursor.Charge,Precursor.Id,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6390_HEK293_GFP1_YZ.raw,...,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6418_HEK293_control2_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6419_HEK293_control3_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6420_HEK293_control4_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6421_HEK293_SerumstarveA_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6422_HEK293_SerumstarveB_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6423_HEK293_RescueA_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6424_HEK293_RescueB_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6425_HEK293_ControlA_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6426_HEK293_ControlB_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6427_HEK293_Pool_phospho_YZ_25uL.raw
Protein.Group,,,,,,,,,,,,,,,,,,,,,
P0CG40,P0CG40,SP9_HUMAN,SP9,Transcription factor Sp9,1,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAASAGGK,3,AAAAAAAAAAAAAAAASAGGK3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P55011,P55011,S12A2_HUMAN,SLC12A2,Solute carrier family 12 member 2,1,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,2,AAAAAAAAAAAAAAAGAGAGAK2,15005.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P55011,P55011,S12A2_HUMAN,SLC12A2,Solute carrier family 12 member 2,1,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3,AAAAAAAAAAAAAAAGAGAGAK3,847115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P35453,P35453,HXD13_HUMAN,HOXD13,Homeobox protein Hox-D13,1,AAAAAAAAAAAAAAASGFAYPGTSER,AAAAAAAAAAAAAAASGFAYPGTSER,3,AAAAAAAAAAAAAAASGFAYPGTSER3,441326.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0A3B3IS91,A0A3B3IS91,PLGRF_HUMAN,POLGARF,POLG alternative reading frame,1,AAAAAAAAAAAAAAATAASAAASAILGGR,AAAAAAAAAAAAAAATAASAAASAILGGR,3,AAAAAAAAAAAAAAATAASAAASAILGGR3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q8N183,Q8N183,NDUF2_HUMAN,NDUFAF2,NADH dehydrogenase [ubiquinone] 1 alpha subcom...,1,YYYIPQYK,YYYIPQYK,2,YYYIPQYK2,1713500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q9H0D6,Q9H0D6,XRN2_HUMAN,XRN2,5'-3' exoribonuclease 2,1,YYYQGCASWK,YYYQGC(UniMod:4)ASWK,2,YYYQGC(UniMod:4)ASWK2,71096.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O00257,O00257,CBX4_HUMAN,CBX4,E3 SUMO-protein ligase CBX4,1,YYYQLNSK,YYYQLNSK,2,YYYQLNSK2,7948.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q93100,Q93100,KPBB_HUMAN,PHKB,Phosphorylase b kinase regulatory subunit beta,1,YYYVPADFVEYEK,YYYVPADFVEYEK,2,YYYVPADFVEYEK2,42400.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P50851,P50851,LRBA_HUMAN,LRBA,Lipopolysaccharide-responsive and beige-like a...,1,YYYWAVNPQDR,YYYWAVNPQDR,2,YYYWAVNPQDR2,20098.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
pg_matrix

,Protein.Names,Genes,First.Protein.Description,N.Sequences,N.Proteotypic.Sequences,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6390_HEK293_GFP1_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6391_HEK293_GFP2_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6392_HEK293_GFP3_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6393_HEK293_GFP4_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6394_HEK293_GSK1_YZ.raw,...,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6418_HEK293_control2_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6419_HEK293_control3_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6420_HEK293_control4_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6421_HEK293_SerumstarveA_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6422_HEK293_SerumstarveB_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6423_HEK293_RescueA_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6424_HEK293_RescueB_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6425_HEK293_ControlA_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6426_HEK293_ControlB_phospho_YZ.raw,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6427_HEK293_Pool_phospho_YZ_25uL.raw
Protein.Group,,,,,,,,,,,,,,,,,,,,,
A0A096LP01,SIM26_HUMAN,SMIM26,Small integral membrane protein 26,2,2,306558.0,277959.0,263439.0,236294.0,328201.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0A0B4J2D5;P0DPI2,GAL3A_HUMAN;GAL3B_HUMAN,GATD3;GATD3B,Putative glutamine amidotransferase-like class...,12,0,79754500.0,85161600.0,84396500.0,75970000.0,83369600.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,488351000.0
A0A0B4J2F0,PIOS1_HUMAN,PIGBOS1,Protein PIGBOS1,1,1,333340.0,512030.0,NaN,NaN,239062.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0A1W2PQ72,MSD7_HUMAN,MSANTD7,Myb/SANT-like DNA-binding domain-containing pr...,6,6,25511.2,NaN,17042.8,28154.9,15986.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0A2Z4LIS9,FXO3B_HUMAN,FOXO3B,Forkhead box protein O3B,4,1,123422.0,100981.0,100807.0,111897.0,87298.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q9Y6X5,ENPP4_HUMAN,ENPP4,Bis(5'-adenosyl)-triphosphatase ENPP4,5,5,365434.0,329469.0,390225.0,386778.0,383522.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q9Y6X8,ZHX2_HUMAN,ZHX2,Zinc fingers and homeoboxes protein 2,11,10,2691240.0,2767690.0,2746250.0,2882180.0,2638810.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q9Y6X9,MORC2_HUMAN,MORC2,ATPase MORC2,24,23,2058820.0,2184980.0,2004320.0,2060600.0,2009310.0,...,300606000.0,99398900.0,99663800.0,98274000.0,194536000.0,96836700.0,35128600.0,236649000.0,286728000.0,116823000.0
Q9Y6Y0,NS1BP_HUMAN,IVNS1ABP,Influenza virus NS1A-binding protein,10,10,826569.0,868970.0,769039.0,783236.0,810710.0,...,14448500.0,10814100.0,11236900.0,2437480.0,NaN,NaN,NaN,9714070.0,6293100.0,5646800.0
Q9Y6Y8,S23IP_HUMAN,SEC23IP,SEC23-interacting protein,30,30,1851480.0,1878880.0,1770050.0,1837560.0,1735140.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
conditions['shortname'] = conditions['Condition'] + "_" + conditions['Replicate'].astype(str) + "_" + conditions['Type']
basenames = list(set(['_'.join(item.split('_')[:-1]) for item in conditions['shortname'].values]))

basenames

['Unstarved_2',
 'GFP_3',
 'SerumStarve_2',
 'Untransfected_1',
 'Unstarved_1',
 'Untransfected_2',
 'Pooled_1',
 'GSK3B_2',
 'SS_Rescue_1',
 'GFP_1',
 'GSK3B_3',
 'GFP_2',
 'SS_Rescue_2',
 'Untransfected_4',
 'Untransfected_3',
 'GSK3B_4',
 'GSK3B_1',
 'SerumStarve_1',
 'GFP_4']

In [39]:
conditions

,Run,Type,Condition,Replicate,shortname
0,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GFP,1,GFP_1_Whole
1,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GFP,2,GFP_2_Whole
2,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GFP,3,GFP_3_Whole
3,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GFP,4,GFP_4_Whole
4,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GSK3B,1,GSK3B_1_Whole
5,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GSK3B,2,GSK3B_2_Whole
6,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GSK3B,3,GSK3B_3_Whole
7,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,GSK3B,4,GSK3B_4_Whole
8,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,Untransfected,1,Untransfected_1_Whole
9,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,Untransfected,2,Untransfected_2_Whole
10,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,Untransfected,3,Untransfected_3_Whole
11,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,Untransfected,4,Untransfected_4_Whole
12,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,SerumStarve,1,SerumStarve_1_Whole
13,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,SerumStarve,2,SerumStarve_2_Whole
14,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,SS_Rescue,1,SS_Rescue_1_Whole
15,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,SS_Rescue,2,SS_Rescue_2_Whole
16,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,Unstarved,1,Unstarved_1_Whole
17,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,Unstarved,2,Unstarved_2_Whole
18,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Whole,Pooled,1,Pooled_1_Whole
19,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GFP,1,GFP_1_Phospho
20,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GFP,2,GFP_2_Phospho
21,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GFP,3,GFP_3_Phospho
22,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GFP,4,GFP_4_Phospho
23,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GSK3B,1,GSK3B_1_Phospho
24,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GSK3B,2,GSK3B_2_Phospho
25,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GSK3B,3,GSK3B_3_Phospho
26,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,GSK3B,4,GSK3B_4_Phospho
27,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,Untransfected,1,Untransfected_1_Phospho
28,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,Untransfected,2,Untransfected_2_Phospho
29,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,Untransfected,3,Untransfected_3_Phospho
30,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,Untransfected,4,Untransfected_4_Phospho
31,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,SerumStarve,1,SerumStarve_1_Phospho
32,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,SerumStarve,2,SerumStarve_2_Phospho
33,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,SS_Rescue,1,SS_Rescue_1_Phospho
34,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,SS_Rescue,2,SS_Rescue_2_Phospho
35,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,Unstarved,1,Unstarved_1_Phospho
36,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,Unstarved,2,Unstarved_2_Phospho
37,D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinase...,Phospho,Pooled,1,Pooled_1_Phospho

In [40]:
experiment = 'GSK3B'
reference = 'GFP'
replicates = 4

In [41]:
def collapse_charges(df):
    """
    Collapse the charge states of the peptides by summing their intensities.
    """

    # 1) Define your peptide‐identity columns (everything that SHOULD stay the same across charge states)
    id_cols = [
        'Protein.Group',
        'Protein.Ids',
        'Protein.Names',
        'Genes',
        'First.Protein.Description',
        'Proteotypic',
        'Stripped.Sequence',
        'Modified.Sequence'
    ]

    # 2) Identify your intensity columns (all the “…_Phospho” and “…_Whole” columns)
    intensity_cols = [c for c in df.columns if c.endswith('_Phospho') or c.endswith('_Whole')]

    collapsed = (
        df
        .groupby(id_cols)[intensity_cols]
        .sum()
        .reset_index()
    )

    # Replace 0 with NaN in the intensity columns
    collapsed[intensity_cols] = collapsed[intensity_cols].replace(0, np.nan)

    return collapsed

# Rename the columns of pr_matrix to match the shortname format
mapping = conditions.set_index('Run')['shortname'].to_dict()

# Create an empty dataframe with the same columns as pr_matrix
occupancy = pd.DataFrame(columns=pr_matrix.columns).rename(columns=mapping)
# Remove the quant columns and replace with the replicates of the reference and experiment
intensity_cols = [col for col in occupancy.columns if col.endswith('_Phospho') or col.endswith('_Whole')]
occupancy.drop(columns=intensity_cols, inplace=True)
# Add the reference and experiment columns
for i in range(1, replicates + 1):
    occupancy[f"{experiment}_{i}"] = np.nan
    occupancy[f"{reference}_{i}"] = np.nan

# Now need a template row to fill in the occupancy dataframe
template_row = pd.Series({col: np.nan for col in occupancy.columns})

precursors = collapse_charges(pr_matrix.rename(columns=mapping))

phospho_peptides = pr_matrix[pr_matrix['Modified.Sequence'].str.contains('UniMod:21')]['Modified.Sequence'].unique()

testindex = 2
p_pep = phospho_peptides[testindex]
# Remove (UniMod:21) from the peptide sequence
p_pep_no_mod = p_pep.replace('(UniMod:21)', '')

unmod_data = precursors[precursors['Modified.Sequence'] == p_pep_no_mod]
mod_data = precursors[precursors['Modified.Sequence'] == p_pep]

# For testing the occupancy calculation
i = 1



# for i in range(1, replicates + 1):
#     ref_occupancy = 

template_row[f"{experiment}_{i}"] = None # Placeholder for the experiment occupancy


# Collapse both dataframes by summing intensities of the charge states


# for p_pep in phospho_peptides:
#     # Remove (UniMod:21) from the peptide sequence
#     p_pep_no_mod = p_pep.replace('(UniMod:21)', '')
    
#     # Get the rows corresponding to this peptide
#     rows = pr_matrix[pr_matrix['Modified.Sequence'] == p_pep]

In [42]:
pr_matrix.columns

Index(['Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description',
       'Proteotypic', 'Stripped.Sequence', 'Modified.Sequence',
       'Precursor.Charge', 'Precursor.Id',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6390_HEK293_GFP1_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6391_HEK293_GFP2_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6392_HEK293_GFP3_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6393_HEK293_GFP4_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6394_HEK293_GSK1_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6395_HEK293_GSK2_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6396_HEK293_GSK3_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6397_HEK293_GSK4_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6398_HEK293_control1_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6399_HEK293_control2_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6400_HEK293_control3_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6401_HEK293_control4_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6402_HEK293_serumStarveA_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6403_HEK293_serumStarveB_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6404_HEK293_rescueA_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6405_HEK293_rescueB_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6406_HEK293_controlA_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6407_HEK293_controlB_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6408_HEK293_pool_YZ_test2.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6409_HEK293_GFP1_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6410_HEK293_GFP2_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6411_HEK293_GFP3_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6412_HEK293_GFP4_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6413_HEK293_GSK3B1_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6414_HEK293_GSK3B2_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6415_HEK293_GSK3B3_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6416_HEK293_GSK3B4_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6417_HEK293_control1_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6418_HEK293_control2_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6419_HEK293_control3_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6420_HEK293_control4_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6421_HEK293_SerumstarveA_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6422_HEK293_SerumstarveB_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6423_HEK293_RescueA_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6424_HEK293_RescueB_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6425_HEK293_ControlA_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6426_HEK293_ControlB_phospho_YZ.raw',
       'D:\MaxQuant_Searches\Major lab\Isaac\YZ_Kinases_06132025\MA6427_HEK293_Pool_phospho_YZ_25uL.raw'],
      dtype='object')

In [43]:
phospho_peptides = pr_matrix[pr_matrix['Modified.Sequence'].str.contains('UniMod:21')]['Modified.Sequence'].unique()
phospho_peptides_no_mod = [item.replace('(UniMod:21)', '') for item in phospho_peptides]

non_mod_peptides = pr_matrix[pr_matrix['Modified']]

KeyError: 'Modified'

In [ ]:
test = 'AAAAAAAATMALAAPS(UniMod:21)SPTPES(UniMod:21)PTMLTK'

# Remove (UniMod:21) from the peptide sequence
test_no_mod = test.replace('(UniMod:21)', '')